// Code generated by go-codegen, DO NOT EDIT.
package adapter

import (
	examples "github.com/alextanhongpin/go-codegen/examples"
	model "github.com/alextanhongpin/go-codegen/examples/model"
	"time"
)

func NewUser(u examples.User) model.User {
	var email string
	if u.Email.Valid {
		email = u.Email.String
	}
	var birthdate time.Time
	if u.Birthdate.Valid {
		birthdate = u.Birthdate.Time
	}
	var confirmationToken string
	if u.ConfirmationToken.Valid {
		confirmationToken = u.ConfirmationToken.String
	}
	var confirmationSentAt time.Time
	if u.ConfirmationSentAt.Valid {
		confirmationSentAt = u.ConfirmationSentAt.Time
	}
	var confirmedAt time.Time
	if u.ConfirmedAt.Valid {
		confirmedAt = u.ConfirmedAt.Time
	}
	var resetPasswordToken string
	if u.ResetPasswordToken.Valid {
		resetPasswordToken = u.ResetPasswordToken.String
	}
	var resetPasswordSentAt time.Time
	if u.ResetPasswordSentAt.Valid {
		resetPasswordSentAt = u.ResetPasswordSentAt.Time
	}
	var currentSignInAt time.Time
	if u.CurrentSignInAt.Valid {
		currentSignInAt = u.CurrentSignInAt.Time
	}
	var lastSignInAt time.Time
	if u.LastSignInAt.Valid {
		lastSignInAt = u.LastSignInAt.Time
	}
	var lastSignOutAt time.Time
	if u.LastSignOutAt.Valid {
		lastSignOutAt = u.LastSignOutAt.Time
	}
	var deletedAt time.Time
	if u.DeletedAt.Valid {
		deletedAt = u.DeletedAt.Time
	}
	return model.NewUser(u.AllowPasswordChange, birthdate, confirmationSentAt, confirmationToken, confirmedAt, u.Country, u.CreatedAt, currentSignInAt, u.CurrentSignInIp, u.CurrentSignInUserAgent, deletedAt, email, u.EmailVerified, u.FamilyName, u.Gender, u.GivenName, u.ID, lastSignInAt, u.LastSignInIp, u.LastSignInUserAgent, lastSignOutAt, u.LastSignOutIp, u.LastSignOutUserAgent, u.Locale, u.Locality, u.MiddleName, u.Name, u.Nickname, u.PhoneNumber, u.PhoneNumberVerified, u.Picture, u.PostalCode, u.PreferredUsername, u.Profile, u.Region, resetPasswordSentAt, resetPasswordToken, u.SignInCount, u.StreetAddress, u.Tags, u.UnconfirmedEmail, u.UpdatedAt, u.Website, u.Zoneinfo)
}
